import Head from "next/head";
import Link from "next/link";

export default function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokemon.jpg" />
      </Head>

      <header className="bg-slate-900 cursor-pointer mb-10">
        <Link href="/">
          <h1 className="text-amber-400 text-5xl text-center py-10">{title}</h1>
        </Link>
      </header>
      <main className="container mx-auto">{children}</main>
      <footer className="flex justify-center items-center mt-10"></footer>
    </>
  );
}
